# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: nice_nano_v2
    shield: corne_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n -DCONFIG_ZMK_DISPLAY=n
    artifact-name: typeractive_nicenano_dongle

  - board: seeeduino_xiao_ble
    shield: corne_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n -DCONFIG_ZMK_DISPLAY=n
    artifact-name: typeractive_xiao_dongle

  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view_custom
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: typeractive_slave_left

#-DCONFIG_ZMK_USB=y -DCONFIG_ZMK_LOG_USB_CDC=y -DCONFIG_LOG=y -DCONFIG_LOG_DEFAULT_LEVEL=3

  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    snippet: studio-rpc-usb-uart
    artifact-name: typeractive_master_left

  - board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_view_custom
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n 
    artifact-name: typeractive_slave_right
        
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: nicenano_settings_reset

  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: xiao_settings_reset
